## World TSP

In [4]:
import pandas as pd
world_tsp = pd.read_csv('world_tsp.csv', skiprows=7, header=None, delim_whitespace=True, error_bad_lines=False)
world_locations = pd.DataFrame()
world_locations['Latitude'] = world_tsp[1][:-1]
world_locations['Longitude'] = world_tsp[2][:-1]
world_locations

/Users/johnlime/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Latitude  Longitude
0        -77.5100   166.4000
1        -64.4300    64.0300
2        -54.9333   -67.6167
3        -54.9333   -68.3333
4        -54.9167   -67.9833
5        -54.9000   -65.9667
6        -54.9000   -66.0000
7        -54.8667   -67.3167
8        -54.8667   -67.8667
9        -54.8500   -67.5167
10       -54.8500   -68.8167
11       -54.8333   -68.5667
12       -54.8333   -68.8167
13       -54.8167   -68.3333
14       -54.8000   -68.3000
15       -54.6167   -65.2333
16       -54.5333   -66.3167
17       -54.5333   -67.2000
18       -54.5333   -67.2833
19       -54.5000   -67.7833
20       -54.4500   -66.5000
21       -54.4167   -67.8667
22       -54.3667   -69.1667
23       -54.3500   -68.1833
24       -54.3333   -66.6667
25       -54.3167   -68.5500
26       -54.2767   -36.5117
27       -54.2667   -66.7667
28       -54.1561   -36.7161
29       -54.0333   -67.3667
...           ...        ...
1904681   77.3614   -68.4642
1904682   77.3775   -67.0819
1904683   77.3833   -71.0667
1904684   77.3833   -72.4667
1904685   77.3894   -67.5297
1904686   77.4167   -72.6667
1904687   77.4239   -66.5747
1904688   77.4275   -70.1892
1904689   77.4894   -69.3322
1904690   77.5097   -66.6478
1904691   77.5325   -67.7672
1904692   77.5567   -68.5850
1904693   77.7167   104.2500
1904694   77.7831   -70.3097
1904695   77.7953   -70.7558
1904696   77.8667   -71.6167
1904697   77.9000    16.6833
1904698   78.0667    14.2333
1904699   78.1833    15.1333
1904700   78.2000    15.6167
1904701   78.2167    15.6333
1904702   78.3167   -72.6333
1904703   78.7833  -103.5333
1904704   78.9333    11.9500
1904705   80.0000   -66.0000
1904706   80.2167   -86.1833
1904707   81.7167   -17.8000
1904708   81.7167   -64.7167
1904709   82.4833   -62.2500
1904710   86.2167    90.0000

[1904711 rows x 2 columns]

In [5]:
loc_num = len(world_locations['Longitude'])
loc_num

1904711

In [8]:
"""Calculating distance between two cities"""
def edge_length(lati, latj, longi, longj):
    q1 = np.cos(latj) * np.sin(longi - longj)
    q3 = np.sin((longi - longj)/2)
    q4 = np.cos((longi - longj)/2)
    q2 = np.sin(lati + latj)*(q3**2) - np.sin(lati - latj)*(q4**2)
    q5 = np.cos(lati - latj)*(q4**2) - np.cos(lati + latj)*(q3**2)
    return int(6378388 * np.arctan2(np.sqrt(q1*q1 + q2*q2), q5) + 1.0)

### Attemps to multithread/process operation

In [12]:
import time
import multiprocessing as mp
from multiprocessing.pool import ThreadPool
import multiprocessing.dummy as mp_dummy

In [33]:
#Single Processor
dim = 10
world_dists = np.empty([dim, dim])#loc_num, loc_num])

start_time = time.time()
for i in range(dim):
    for j in range(dim):
        world_dists[i][j] = edge_length(world_locations['Latitude'][i], world_locations['Latitude'][j], world_locations['Longitude'][i], world_locations['Longitude'][j])
print(time.time() - start_time)
        
print(world_dists)

0.017001867294311523
[[1.0000000e+00 3.5004580e+06 1.6568143e+07 1.6760832e+07 1.6697505e+07
  1.6093742e+07 1.6092357e+07 1.6302111e+07 1.6676280e+07 1.6398652e+07]
 [3.5004580e+06 1.0000000e+00 1.9584413e+07 1.9588888e+07 1.9473935e+07
  1.9576883e+07 1.9571075e+07 1.9179591e+07 1.9154927e+07 1.9059665e+07]
 [1.6568143e+07 1.9584413e+07 1.0000000e+00 1.9933700e+05 1.6105800e+05
  5.9136400e+05 5.8337400e+05 4.4546000e+05 4.3928300e+05 5.3349200e+05]
 [1.6760832e+07 1.9588888e+07 1.9933700e+05 1.0000000e+00 1.5700100e+05
  7.2747000e+05 7.2285300e+05 6.0927700e+05 4.7274500e+05 6.5443500e+05]
 [1.6697505e+07 1.9473935e+07 1.6105800e+05 1.5700100e+05 1.0000000e+00
  7.5220800e+05 7.4436100e+05 4.6896200e+05 3.2474400e+05 4.9886500e+05]
 [1.6093742e+07 1.9576883e+07 5.9136400e+05 7.2747000e+05 7.5220800e+05
  1.0000000e+00 1.6523000e+04 7.7089800e+05 9.8809700e+05 9.4537700e+05]
 [1.6092357e+07 1.9571075e+07 5.8337400e+05 7.2285300e+05 7.4436100e+05
  1.6523000e+04 1.0000000e+00 7.55977

In [ ]:
#Multiprocessing
results = np.empty([dim, dim])#loc_num, loc_num])
dim = 10
part = 2
pool = mp.Pool()
def function(segment):
    for i in range(segment):
        for j in range(dim):
            world_dists[i][j] = edge_length(world_locations['Latitude'][i], world_locations['Latitude'][j], world_locations['Longitude'][i], world_locations['Longitude'][j])

for function(
            
start_time = time.time()
results = pool.apply(function, args=dim/part*seg) for seg in range(part)
# results = np.array([[pool.apply(edge_length, args=(world_locations['Latitude'][i], world_locations['Latitude'][j], world_locations['Longitude'][i], world_locations['Longitude'][j])) for j in range(dim)] for i in range(dim)])
print(time.time() - start_time)

print(results)

In [15]:
#Multithreading
dim = 10
results = np.empty([dim, dim])#loc_num, loc_num])
thread_pool = ThreadPool()

start_time = time.time()
results = np.array([[thread_pool.apply(edge_length, args=(world_locations['Latitude'][i], world_locations['Latitude'][j], world_locations['Longitude'][i], world_locations['Longitude'][j])) for j in range(dim)] for i in range(dim)])
print(time.time() - start_time)
#2: 235.67695999145508
#4: 229.57316517829895
#8: 230.3890721797943
print(results)

0.028398990631103516
[[       1  3500458 16568143 16760832 16697505 16093742 16092357 16302111
  16676280 16398652]
 [ 3500458        1 19584413 19588888 19473935 19576883 19571075 19179591
  19154927 19059665]
 [16568143 19584413        1   199337   161058   591364   583374   445460
    439283   533492]
 [16760832 19588888   199337        1   157001   727470   722853   609277
    472745   654435]
 [16697505 19473935   161058   157001        1   752208   744361   468962
    324744   498865]
 [16093742 19576883   591364   727470   752208        1    16523   770898
    988097   945377]
 [16092357 19571075   583374   722853   744361    16523        1   755977
    976728   931011]
 [16302111 19179591   445460   609277   468962   770898   755977        1
    384371   185190]
 [16676280 19154927   439283   472745   324744   988097   976728   384371
         1   284872]
 [16398652 19059665   533492   654435   498865   945377   931011   185190
    284872        1]]


In [ ]:
np.save(world_dists)

In [21]:
import multiprocessing as mp
import random
import string
import time

random.seed(123)

# Define an output queue
output = mp.Queue()

# define a example function
def rand_string(length, output):
    """ Generates a random string of numbers, lower- and uppercase chars. """
    rand_str = ''.join(random.choice(
                        string.ascii_lowercase
                        + string.ascii_uppercase
                        + string.digits)
                   for i in range(length))
    output.put(rand_str)

# Setup a list of processes that we want to run
processes = [mp.Process(target=rand_string, args=(5, output)) for x in range(400)]

start_time = time.time()
# Run processes
for p in processes:
    p.start()

# Exit the completed processes
for p in processes:
    p.join()
print(time.time() - start_time)
    
# Get process results from the output queue
results = [output.get() for p in processes]

print(results)

"""Single"""
start_time = time.time()
result_single = []
for i in range(400):
    rand_str = ''.join(random.choice(
                            string.ascii_lowercase
                            + string.ascii_uppercase
                            + string.digits)
                       for i in range(5))
    result_single.append(rand_str)
print(time.time() - start_time)
print(result_single)

1.7486438751220703
['l206j', 'y9rNS', 'p1TKU', 'kgXhd', 'Qt1LN', 'cfNAc', '8jFxX', '0O22e', 'COml6', 'lZyoK', '40qXg', 'l9zGJ', 't9oGV', 'ivNJr', '0AtCK', 'XeeF7', 'kfPzE', 'pEEJH', 'byaeE', 'I2O6z', 'tnUQT', 'lcCfP', '0tKTy', 'r6gBi', 'z8Tuz', 'QbZOw', '4oYkt', 'SMbl9', 'BnhD2', '7AQED', 'hqyGp', 'rr7wE', 'ZyEzp', 'ECiQK', 'FU6WP', 'O4yzv', 'eRJLC', '8mqpb', '5KWEo', 'gaqsA', 'IeeLY', '8Xz8d', 'OWNOH', 'pAueM', 'rTkWw', '5AQ7a', 'S109B', 'TUO5e', 'A7EeL', 'DSbnD', 'whzI9', 'qO7ip', '3f94z', 'TPwJ3', '9eOXM', 'EYTfy', 'efH5T', 'SQFB0', '3NXQ3', 'eVAgw', 'Vqawm', 'GgMZY', '36cH3', 'K5xIM', 'P5PDx', 'uqsE8', '4kjG4', 'Uo24K', '4x71C', 'fup1P', 'PGUOJ', 'At8Zw', 'waQmn', 'MySl0', 'tl5k8', '9tMkR', 'RQULN', 'OYpPO', 'z7B4o', '5antq', 'e4rId', 'KBcXv', 'sh3Wq', '5HWQJ', 'dCwyW', 'JZwpg', 'hmxyL', 'zcyGs', 'p58Oe', 'dkUp0', '1T8ZN', '4KPo0', 'zxJkw', '5ujHV', 'aqY60', 'wbiAH', 'EOPNW', 'R3zca', 'T6zO8', 'L2xPW', 'IC1Xq', '8OffC', 'QmyF9', 'gaIVU', 'rQCR2', 'H2QQj', '3Jc99', 'CxeVi', 'CtZgO',

# Implementation

In [2]:
import random
import numpy as np

class TSPGeneticAlgorithm:
    def __init__(self, tsp_graph, population_size):
        self.TSP = tsp_graph
        self.city_num = np.shape(self.TSP)[0]
        self.pop_size = population_size
        self.score = np.empty(self.pop_size)
        
        """Route will start from zero"""
        self.genotype_pool = np.zeros([self.pop_size, self.city_num+1], dtype = int)
        for i in range(self.pop_size):
            city_indices = np.array(range(1, self.city_num))
            np.random.shuffle(city_indices)
            self.genotype_pool[i][1:self.city_num] = city_indices
        
        self.best_score = 0
        self.best_route = np.empty(self.city_num+1)
            
    def score_function(self):
        for i in range(self.pop_size):
            tmp_score = 0
            for k in range(self.city_num):
                tmp_score += self.TSP[self.genotype_pool[i][k], self.genotype_pool[i][k+1]]
            self.score[i] = tmp_score
            
        #Update Best Score and Route
        self.best_score = np.amin(self.score)
        self.best_route = self.genotype_pool[np.argsort(self.score)[0]]
        print("Shortest Distance: ", self.best_score)
        print("Best Route: ", self.best_route)
        return self.score
    
    def parent_genes(self, number_of_parents):
        fitness = 1/self.score
        survival_probability = fitness/np.sum(fitness)
        parent_genotype = self.genotype_pool[np.random.choice(range(self.pop_size), number_of_parents, replace=False, p=survival_probability)]
        return parent_genotype
    
    def elitism(self, number_of_elites):
        return self.genotype_pool[np.argsort(self.score)[:number_of_elites]]

    def crossover(self, parent_gene_a, parent_gene_b):
        """
        INPUT: (1, gene_length)Numpy Ndarray: 2 Parent Genes
        OUTPUT: (1, gene_length)Numpy Ndarray: 2 Child Gene
        """
        def child(_a, _b):
            snippets = sorted(random.sample(range(1, self.city_num), 2))
            offspring_a = _a[snippets[0]:snippets[1]]
            offspring_b = _b
            offspring_b = np.setdiff1d(offspring_b, offspring_a)
            
            child_gene = offspring_b[:snippets[0]]
            child_gene = np.append(child_gene, offspring_a)
            child_gene = np.append(child_gene, offspring_b[snippets[0]:])
            child_gene = np.append(child_gene, 0)
            return child_gene
        
        child_genotype = child(parent_gene_a, parent_gene_b)
        child_genotype = np.stack((child_genotype, child(parent_gene_b, parent_gene_a)))
        return child_genotype
              
    def mutation(self, parent_gene):
        """
        INPUT: (1, gene_length)Numpy Ndarray: Parent Gene
        OUTPUT: (1, gene_length)Numpy Ndarray: Child Gene
        """
        snippets = random.sample(range(1, self.city_num), 2)
        child_gene = parent_gene
        child_gene[0][snippets[0]] = parent_gene[0][snippets[1]]
        child_gene[0][snippets[1]] = parent_gene[0][snippets[0]]
        return child_gene
    
    def optimization(self, iterations, number_of_elites, number_of_parents, crossover_rate = 0.7):
        for i in range(iterations):
            self.score_function()
            parents = self.parent_genes(number_of_parents)
            nextgen = self.elitism(number_of_elites)
            for j in range(int(self.pop_size*crossover_rate)):
                a_index, b_index = random.sample(range(number_of_parents), 2)
                tmp_children = self.crossover(parents[a_index], parents[b_index])
                nextgen = np.append(nextgen, tmp_children, axis=0)
            for j in range(self.pop_size - number_of_elites - int(self.pop_size * crossover_rate)):
                chosen_parent = random.sample(range(number_of_parents), 1)
                tmp_children = self.mutation(parents[chosen_parent])
                nextgen = np.append(nextgen, tmp_children, axis=0)
            self.genotype_pool= nextgen
                
        self.score_function()

In [3]:
graph = np.array([[0, 10, 15, 20], [5, 0, 9, 10], [6, 13, 0, 12], [8, 8, 9, 0]])
print(graph)
ga = TSPGeneticAlgorithm(graph, 20)
print(ga.genotype_pool)
ga.optimization(30, 5, 2)

[[ 0 10 15 20]
 [ 5  0  9 10]
 [ 6 13  0 12]
 [ 8  8  9  0]]
[[0 3 2 1 0]
 [0 2 1 3 0]
 [0 1 2 3 0]
 [0 1 2 3 0]
 [0 1 3 2 0]
 [0 2 3 1 0]
 [0 2 1 3 0]
 [0 1 3 2 0]
 [0 2 3 1 0]
 [0 1 3 2 0]
 [0 2 1 3 0]
 [0 3 2 1 0]
 [0 1 3 2 0]
 [0 1 3 2 0]
 [0 1 2 3 0]
 [0 3 2 1 0]
 [0 2 1 3 0]
 [0 3 1 2 0]
 [0 3 1 2 0]
 [0 3 2 1 0]]
Shortest Distance:  35.0
Best Route:  [0 1 3 2 0]
Shortest Distance:  35.0
Best Route:  [0 1 3 2 0]
Shortest Distance:  35.0
Best Route:  [0 1 3 2 0]
Shortest Distance:  35.0
Best Route:  [0 1 3 2 0]
Shortest Distance:  35.0
Best Route:  [0 1 3 2 0]
Shortest Distance:  35.0
Best Route:  [0 1 3 2 0]
Shortest Distance:  35.0
Best Route:  [0 1 3 2 0]
Shortest Distance:  35.0
Best Route:  [0 1 3 2 0]
Shortest Distance:  35.0
Best Route:  [0 1 3 2 0]
Shortest Distance:  35.0
Best Route:  [0 1 3 2 0]
Shortest Distance:  35.0
Best Route:  [0 1 3 2 0]
Shortest Distance:  35.0
Best Route:  [0 1 3 2 0]
Shortest Distance:  35.0
Best Route:  [0 1 3 2 0]
Shortest Distance:  35.0
Bes